# lovelace_gen

type: custom:config-template-card
entities:
  - sensor.max_temp
  - sensor.min_temp

card:

    type: custom:mini-graph-card
    hours_to_show: 96
    {% raw %}
    upper_bound: "${this.hass.states['sensor.max_temp'].state}"
    lower_bound: "${this.hass.states['sensor.min_temp'].state}"
    {% endraw %}
    line_width: 3
    color_thresholds:
      - value: 14
        color: "#FFFF00"
      - value: 18
        color: "#FFA500"
      - value: 22
        color: "#FF0000"
      - value: 26
        color: "#8B0000"
    height: 150
    font_size: 60
    show:
      name: false
      icon: false
      labels: true

    entities:
      - entity: sensor.{{ room }}_temperature
        name: Temp
        show_state: true

      - entity: sensor.1_week_{{ room }}_temperature
        name: 7 day avg
        show_fill: false
        show_state: true
        show_points: false

      - entity: sensor.daytime
        name: Night
        show_line: false
        show_points: false
        show_legend: false
        y_axis: secondary
        color: lightsteelblue

    style: |
      ha-card {
        border-radius: 0;
        drop-shadow: none;
        padding-bottom: 2px;
      }

      .info.flex {
        display: contents;
      }