# custom_header:
#   compact_mode: true
#   elements_color: "#424242"
#   background: >-
#     {% if states('binary_sensor.kitchendoorlock') == 'on' or states('binary_sensor.loungedoorlock') == 'on' %}
#     rgb(255,53,23,1)
#     {% else %}
#     rgb(105,199,252,.9)
#     {% endif %}
#   view_css: "background-blend-mode: overlay;"
#   panel_view_css: "background-blend-mode: overlay;"
#   active_tab_color: "#fed911"
#   tab_indicator_color: "#fed911"
#   header_text: >-
#     {% if states('binary_sensor.kitchendoorlock') == 'on' %}
#     The kitchen door's unlocked
#     {% elif states('binary_sensor.loungedoorlock') == 'on' %}
#     The front door's unlocked
#     {% else %}
#     Home Assistant
#     {% endif %}


views: # split these out to make the files more manageable
  - !include viewfiles/view_mobile_remote.yaml
  - !include viewfiles/view_mobile_broadcast.yaml
  - !include viewfiles/view_mobile_whereabouts.yaml
  - !include viewfiles/view_mobile_controls.yaml
  - !include viewfiles/view_mobile_info.yaml
  - !include viewfiles/view_mobile_camera.yaml
 
